# Generated by Django 4.0.6 on 2022-07-13 21:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Floor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('no_of_slots', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Slot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('floor_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='floor.floor')),
            ],
        ),
        migrations.CreateModel(
            name='Slot_status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.BooleanField(default=False)),
                ('slot_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='floor.slot')),
            ],
        ),
    ]
